-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS bootcamp.events
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    user_id uuid NOT NULL,
    type integer NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    all_day boolean NOT NULL DEFAULT true,
    CONSTRAINT events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bootcamp.exercises
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    content_file text COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    work_days numeric(3, 1) NOT NULL,
    rtl boolean NOT NULL DEFAULT false,
    CONSTRAINT exercises_pkey PRIMARY KEY (id),
    CONSTRAINT exercises_code_key UNIQUE (content_file)
);

CREATE TABLE IF NOT EXISTS bootcamp.recruit_exercises
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    recruit_id uuid NOT NULL,
    exercise_id uuid NOT NULL,
    status integer NOT NULL DEFAULT 0,
    start_date timestamp with time zone,
    cr_date timestamp with time zone,
    fix_date timestamp with time zone,
    done_date timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT recruit_exercises_pkey PRIMARY KEY (id),
    CONSTRAINT recruit_exercises_recruit_id_exercise_id_key UNIQUE (recruit_id, exercise_id)
);

CREATE TABLE IF NOT EXISTS bootcamp.team_exercises
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    team_id uuid NOT NULL,
    exercise_id uuid NOT NULL,
    "position" integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT team_exercises_pkey PRIMARY KEY (id),
    CONSTRAINT uq_team_exercise UNIQUE (team_id, exercise_id)
);

CREATE TABLE IF NOT EXISTS bootcamp.teams
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT teams_pkey PRIMARY KEY (id),
    CONSTRAINT teams_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS bootcamp.users
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    username text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    role integer NOT NULL DEFAULT 2,
    team_id uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_username_key UNIQUE (username)
);

ALTER TABLE IF EXISTS bootcamp.events
    ADD CONSTRAINT events_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES bootcamp.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_events_user_id
    ON bootcamp.events(user_id);


ALTER TABLE IF EXISTS bootcamp.recruit_exercises
    ADD CONSTRAINT recruit_exercises_exercise_id_fkey FOREIGN KEY (exercise_id)
    REFERENCES bootcamp.exercises (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_recruit_exercises_exercise_id
    ON bootcamp.recruit_exercises(exercise_id);


ALTER TABLE IF EXISTS bootcamp.recruit_exercises
    ADD CONSTRAINT recruit_exercises_recruit_id_fkey FOREIGN KEY (recruit_id)
    REFERENCES bootcamp.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_recruit_exercises_recruit_id
    ON bootcamp.recruit_exercises(recruit_id);


ALTER TABLE IF EXISTS bootcamp.team_exercises
    ADD CONSTRAINT team_exercises_exercise_id_fkey FOREIGN KEY (exercise_id)
    REFERENCES bootcamp.exercises (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_team_exercises_exercise_id
    ON bootcamp.team_exercises(exercise_id);


ALTER TABLE IF EXISTS bootcamp.team_exercises
    ADD CONSTRAINT team_exercises_team_id_fkey FOREIGN KEY (team_id)
    REFERENCES bootcamp.teams (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS ix_team_exercises_team_id
    ON bootcamp.team_exercises(team_id);


ALTER TABLE IF EXISTS bootcamp.users
    ADD CONSTRAINT users_team_id_fkey FOREIGN KEY (team_id)
    REFERENCES bootcamp.teams (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS ix_users_team_id
    ON bootcamp.users(team_id);

END;